name: スクレイピングしてページを組み立ててデプロイする
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9,21 * * *"
  push:
    branches: # any branches
      - '**'
jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.jsのインストール
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: スクレイピング開始
        run: |
          npm ci
          npm start
        env:
          LOGIN_INFO: ${{ secrets.LOGIN_INFO }}
      - name: cnameファイルの追加
        run: echo 'osakashi-library.penpen-dev.com' > CNAME
      - name: Gitの設定とcommit
        run: |
          git config --local user.email "penpen@gmail.com"
          git config --local user.name "penpen-bot"
          git checkout -b gh-pages
          git add .
          git commit -m `TZ=Asia/Tokyo date "+%Y%m%d_%H%M"`
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
