name: スクレイピングしてページを組み立ててデプロイする
on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"
  push:
    branches:
      - '**'
jobs:
  deploy:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start Scraping
        run: |
          npm ci
          npm start
        env:
          LOGIN_INFO: ${{ secrets.LOGIN_INFO }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: osakashi-library.penpen-dev.com
